version: "3.7"

services:
  web:
    build: .
    ports:
      - 3020:3020
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py makemigrations &&
             python3 ./manage.py migrate &&
             gunicorn config.wsgi:application -b 0.0.0.0:3020"
    env_file:
      - ./.env